### ISSUE TITLE
Integer variable min-max value is too limited

### ISSUE THREAD

**Issue by RailKill** [atomic-junky/Monologue#12]
# Use Case
Negative numbers are a thing, and plenty of conversation flow may use values above 100.

# Current Implementation
The user can type in any value in the Integer variable spinner box:

![beforeint](https://github.com/user-attachments/assets/66a80ee6-d002-4d44-9118-642d27685421)

But after exiting focus or pressing enter, the spinner will confine the value for Integer variables in RootNode, ActionNode or ConditionNode between 0 to 100.

![afterint](https://github.com/user-attachments/assets/9b2e5bdd-74e6-4449-a482-c14e4e7740e4)

# Proposed Implementation
Use Godot engine's actual min-max value for 64-bit int.

**Comment by atomic-junky** [comment]
It's "fixed" in #38
