### ISSUE TITLE
EndPathNode does not go to next story in Test

### ISSUE THREAD

**Issue by RailKill** [atomic-junky/Monologue#13]
**Version:** Tested in v2.1.2, still present in v2.2.3
**Severity:** Medium

# Steps to Reproduce
1. Create an EndPathNode.
2. Edit next story to a file name (with or without ".json" suffix) in the same directory as the current file.

![nextstory4](https://github.com/user-attachments/assets/66033718-506e-4c7a-a11a-eaf2e6de8aaa)

![nextstory1](https://github.com/user-attachments/assets/cec9191d-4ab9-4644-a966-4a198dc3894a)

![nextstory2](https://github.com/user-attachments/assets/70c2cd6b-b8db-433d-bae9-5259c5b82601)

3. Start test and proceed to EndPathNode.

# Current Behavior
Test does not go to next story and just freezes.

![nextstory3](https://github.com/user-attachments/assets/9a8cfebd-c63a-4583-9d77-d68bde32c3f6)

# Expected Behavior
Should load next json file and play it, keeping any variable values from the previous json play. If I understand correctly, if the next json has the same variable names, their default values will simply be replaced by any previous values stored in the Test run.

**Comment by atomic-junky** [comment]
Maybe I forgot to implement this (or maybe it's just not working) 😅
