### ISSUE TITLE
Revert property crash

### ISSUE THREAD

**Issue by atomic-junky** [atomic-junky/Monologue#23]
When you delete the selected node with the delete shortcut and you do Ctrl+Z after the program will crash.
The program stop at the line 32 in PropertyHistory.gd where the variable node can be null.

![image](https://github.com/user-attachments/assets/6daca487-d67f-488a-8ea2-d91e98e1ca79)

**Comment by atomic-junky** [comment]
This problem is quite critical, since pressing SUPPR while editing a RichTextLabel or LineEdit deletes the node.

**Comment by RailKill** [comment]
does this still happen after the #22 merge? that PR should fix the `Delete` hotkey timing

**Comment by atomic-junky** [comment]
My bad, you've perfectly fixed it! 😅
