### ISSUE TITLE
Interface redesign

### ISSUE THREAD

**Issue by atomic-junky** [atomic-junky/Monologue#37]
Monologue is becoming more and more complex, and tends to become even more so. It is therefore necessary to revise the interface to make the software more user-friendly. Also, with the addition of new features and elements, the interface has become messy and inconsistent.

The aim of this issue is to discuss possible changes. It is linked to the `feature/ui-redesign` branch.

**Comment by atomic-junky** [comment]
The window title bar has been reworked and everything is hardcoded because we are unable to extend the content of the window to the title bar due to Godot limitation.  However, the implementation of this feature in Godot is being discussed and some people are working on it here: https://github.com/godotengine/godot-proposals/issues/4846.

The window looks like this for now:
![image](https://github.com/user-attachments/assets/6a620288-5584-4baa-a160-af962a643383)

**Comment by atomic-junky** [comment]
Hi, I'm back!
With the redesign of the interface I wanted to redo the logo (which was a bit random). For that I thought an asteroid would look pretty good. So here's what I did:

# Purple Asteroid
![image](https://github.com/user-attachments/assets/0e480c17-0c6a-4cc4-a57e-642b27350b7f)
![image](https://github.com/user-attachments/assets/025bbc1f-2af6-4997-9921-87f18c537558)
![image](https://github.com/user-attachments/assets/967789a1-973d-4e74-8f65-b25b540a060e)

# Red Asteroid
![image](https://github.com/user-attachments/assets/c76f9b22-85bd-411b-b63a-170289977422)
![image](https://github.com/user-attachments/assets/0e3b4b5d-b445-4eb2-883b-b8e081a9bdea)
![image](https://github.com/user-attachments/assets/fc9e7c83-26ac-456f-b5a9-49e1b262c33d)

# The Complex Asteroid
![image](https://github.com/user-attachments/assets/6e6ca58e-401b-4b9c-ac61-475aeded5204)
It's too complex to be the logo, but it could be used for other things.

Please, tell me which one you like best or if you have other suggestions.
*(The banners in the screenshots are just placeholders and the logo designs are really inspired by Kurzgesagt..)*

**Comment by RailKill** [comment]
Looks really good so far! Can we keep the dinosaur? I think a mascot gives the application some charm, plus it's a good throwback to v2.x. It can be a new dinosaur instead of the old one.

**Comment by atomic-junky** [comment]
Of course, I made an asteroid because I thought it made sense with ‘Monologue’ but we can keep a dinosaur. I don't think we should keep the same one as in 2.x but if we do another one, which dinosaur and in which style? Do you have any ideas?

**Comment by RailKill** [comment]
I'm not sure either, it has absolutely no effect but I just feel that a dinosaur should still appear in the splash screen 😂 I made a quick dinosaur head .svg using the color palette from the asteroid in hope to spark some ideas. Feel free to scrap this if it doesn't look good.

<img src="https://github.com/user-attachments/assets/21615656-cc77-4369-8ae7-b2ea558901a1" width=256 />

---
Mini dinosaur icon:

<img src="https://github.com/user-attachments/assets/a0b4a1b1-d2cd-4790-b441-cdda7c68dbdd" width=64 />

**Comment by atomic-junky** [comment]
Unfortunately I wasn't very inspired, but I did clean up your version of the dinosaur a bit and made two other small versions. Let me know what you think.
![icon](https://github.com/user-attachments/assets/c5799402-107f-40b3-8722-4adf91342615)
![icon](https://github.com/user-attachments/assets/6b43daa1-a3bb-429c-8077-0573ba38cd05)
![Frame 19](https://github.com/user-attachments/assets/c2d280c5-dfb8-4267-a05a-87fd89b487df)

**Comment by atomic-junky** [comment]
Thanks! I'll try to make a version that look good for an application. I think we'll have enough time to find a good version before v3 is ready.

**Comment by atomic-junky** [comment]
I did some tests and came up with this proposal. What do you think?
This is the current branding on the branch, if you want to see what it looks like.
![Monlologue artboard](https://github.com/user-attachments/assets/ed9a909f-151d-49cd-aaba-08941e146370)
![Artboard](https://github.com/user-attachments/assets/00e4045a-a0ec-4926-8c43-7c112b24b506)

**Comment by RailKill** [comment]
amazing! it looks really good!
