### ISSUE TITLE
Add voiceline field and AudioPlayer designated for SentenceNodes

### ISSUE THREAD

**Issue by RailKill** [atomic-junky/Monologue#6]
I'm proposing some enhancement requests here that are involve the direction/architecture of Monologue; these aren't just bug fixes so I think it's good to discuss first.

# Use Case
Handling of voice lines for sentences. Developers mainly tie a voice line to each line of dialogue, whether in .csv or .json, they go hand-in-hand.

# Current Implementation
The user has to create an ActionNode set to PlayAudio before every SentenceNode to play voice lines. This also has a clear separation between audio and dialogue, which doesn't reflect how a real developer organizes voice lines to dialogue.

# Proposed Implementation
![voice_sentence](https://github.com/user-attachments/assets/de80e836-94be-42a0-87a3-443440e109e1)

Add an additional `Voiceline` field in SentenceNodePanel for the user to specify a sound file there. Then, add AudioPlayer to the Test story to play it because the user can skip dialogue lines, so audio playback is somewhat controlled by user skips. Whereas ActionNode PlayAudio shall be used for sound effects and other ambient stuff that would not stop abruptly just because a dialogue skip occurred.

**Comment by atomic-junky** [comment]
It's a good idea!

**Comment by atomic-junky** [comment]
![image](https://github.com/user-attachments/assets/9b4d14ea-96a8-41d2-a205-de86f164560d)

I made a button to select a file

**Comment by RailKill** [comment]
that's awesome! i think allowing LineEdit to be editable + filepicker is good. i would certainly want the ability to specify a relative path in Voiceline, not just absolute path.

i have a small UX concern about the consistency with ActionNode's PlayAudio which grabs audio files from `assets/audios`. for example, when the user types in a filename into Voiceline, like `voice.mp3`, does it look for the file in `assets/voicelines/voice.mp3`? if it does, it feels weird to have many hardcoded relative paths like that and raises future concerns on how many hardcoded paths we should have. if it doesn't, then it's inconsistent with PlayAudio, so it's confusing.

personally, i would remove the hardcoded path in PlayAudio and CustomBackground, so the user is the one who has to specify the relative folder paths from the .json. this was my expectation when i first used Monologue, and i think generally people don't expect hardcoded paths too. the downside is that it breaks the old structure, so we have to update the MrSharpener example. users who used PlayAudio would also have to update on their end.

so for the MrSharpener example, previously we write like this in PlayAudio value field (path is hardcoded):
```
sound.mp3
```
but after the change we have to write like this (path is not hardcoded, so the user has to write it out themselves):
```
assets/audios/sound.mp3
```
this is just my suggestion. how you'd like Monologue to behave is up to you of course. hope this gives you some insight!

**Comment by atomic-junky** [comment]
I think it's a good idea, hardcoded paths are too restrictive

**Comment by RailKill** [comment]
yea we can probably check from .json first before checking the hardcoded path. we can ensure compatibility by checking `assets/audios` at the very end, only if the file doesn't exist

so if `sound.mp3` doesn't exist in the same directory as the .json, look for it in `assets/audios`
