### ISSUE TITLE
Add action history for undo/redo functionality

### ISSUE THREAD

**Issue by RailKill** [atomic-junky/Monologue#7]
# Use Case
Quality of life.

# Current Implementation
No action history. If the user accidentally deletes a node, they have to reload the file before save. I believe this functionality is important for serious users who want to use Monologue as a key part of their workflow.

# Proposed Implementation
`MonologueNodePanel` and `GraphEdit` should keep track of its own history (let's say 20 actions each). If the user is in SentenceNodePanel (basically if that panel is visible), then undo/redo only affects that SentenceNodePanel. If the user is in the GraphEdit (when side panel is not visible), then undo/redo affects that GraphEdit. This way, different GraphEdits (different tabs) will also keep track of its own action history.

This means UI controls within the individual side node panel or graph will need to connect to the "changed" signal, so whenever a change is detected, it adds it to the list of actions. For LineEdits and TextEdits, it is better to refactor them to only trigger on focus_exited, otherwise it will populate the history incredibly quickly for every character typed. There are some additional actions such as adding and deleting of graph nodes that need to be handled slightly differently for undo/redo.

Proposed default hotkey to trigger undo/redo is `Ctrl + Z` and `Ctrl + Shift + Z` respectively, following the convention of the Save hotkey (`Ctrl + S`). Anticipated type of actions to keep track of are as follows:

- Changes in any LineEdit, TextEdit, OptionButton (dropdowns), radio buttons, checkboxes
- Adding and deleting options in ChoiceNode
- Connecting and disconnecting graph nodes (be wary of stuff like connection_from_empty which handles both creation and connection at once)
- Adding and deleting graph nodes

**Comment by atomic-junky** [comment]
That would be amazing, I think the code is too messy but if you can do it that would be super helpful! I can help if needed but I don't have much time at the moment

**Comment by RailKill** [comment]
implementation merged #10
